-- Candlesticks initial schema.
--
-- One OHLC candlestick per (numerator, denominator, duration, time,
-- retrieval); the retrieval links every bar back to the data source that
-- produced it.  Primary keys are version-4 UUIDs generated by
-- gen_random_uuid(), which is built into PostgreSQL 13 and later and lives
-- in pg_catalog, so it is available from any schema without an extension.
--
-- Data sources are who told us (CoinGecko, Yahoo Finance).  Exchanges are
-- where it traded (NASDAQ, Binance, Uniswap V3).  Those are not the same
-- thing, and a source can report many exchanges.  A "market" in the
-- pair-on-an-exchange sense is the candlestick's numerator/denominator
-- plus the exchange; a dedicated markets table can wait.

create table if not exists instrument_types (
    id          uuid                     primary key default gen_random_uuid(),
    name        varchar                  not null unique,
    description varchar,
    created_at  timestamp with time zone not null default now()
);
--;;
create table if not exists data_source_kinds (
    id          uuid                     primary key default gen_random_uuid(),
    name        varchar                  not null unique,
    description varchar,
    created_at  timestamp with time zone not null default now()
);
--;;
create table if not exists exchanges (
    id           uuid                     primary key default gen_random_uuid(),
    name         varchar                  not null unique,
    display_name varchar,
    mic          varchar                  unique,
    chain        varchar,
    description  varchar,
    created_at   timestamp with time zone not null default now()
);
--;;
create index if not exists exchanges_chain_index on exchanges (chain);
--;;
create table if not exists instruments (
    id                  uuid                     primary key default gen_random_uuid(),
    name                varchar,
    instrument_type_id  uuid                     references instrument_types (id),
    created_at          timestamp with time zone not null default now(),
    updated_at          timestamp with time zone not null default now()
);
--;;
create index if not exists instruments_type_index on instruments (instrument_type_id);
--;;
create table if not exists data_sources (
    id                   uuid                     primary key default gen_random_uuid(),
    name                 varchar                  not null unique,
    data_source_kind_id  uuid                     references data_source_kinds (id),
    created_at           timestamp with time zone not null default now()
);
--;;
create index if not exists data_sources_kind_index on data_sources (data_source_kind_id);
--;;
create table if not exists tickers (
    id              uuid                     primary key default gen_random_uuid(),
    instrument_id   uuid                     not null references instruments (id),
    data_source_id  uuid                     not null references data_sources (id),
    exchange_id     uuid                     references exchanges (id),
    symbol          varchar                  not null,
    canonical       varchar                  not null,
    valid_from      timestamp with time zone not null default '-infinity',
    valid_to        timestamp with time zone,
    created_at      timestamp with time zone not null default now(),
    check (valid_to is null or valid_to > valid_from)
);
--;;
-- Same (source, canonical, exchange) may be reused across non-overlapping
-- windows (old GM vs new GM).  IS NOT DISTINCT FROM treats a null exchange
-- as a real key value, the way UNIQUE NULLS NOT DISTINCT did.
create or replace function tickers_no_overlap () returns trigger as $$
begin
    if exists (
        select 1 from tickers t
        where t.id is distinct from new.id
          and t.data_source_id = new.data_source_id
          and t.canonical = new.canonical
          and t.exchange_id is not distinct from new.exchange_id
          and tstzrange(t.valid_from, t.valid_to, '[)') &&
              tstzrange(new.valid_from, new.valid_to, '[)')
    ) then
        raise exception
            'overlapping ticker validity window for %, source %, exchange %',
            new.canonical, new.data_source_id, new.exchange_id;
    end if;
    return new;
end;
$$ language plpgsql;
--;;
drop trigger if exists tickers_no_overlap_trigger on tickers;
--;;
create trigger tickers_no_overlap_trigger
    before insert or update on tickers
    for each row execute procedure tickers_no_overlap();
--;;
create index if not exists tickers_instrument_index on tickers (instrument_id);
--;;
create index if not exists tickers_canonical_index on tickers (canonical);
--;;
create index if not exists tickers_exchange_index on tickers (exchange_id);
--;;
create index if not exists tickers_lookup_index
    on tickers (data_source_id, canonical, valid_from);
--;;
create table if not exists candlestick_durations (
    id         uuid                     primary key default gen_random_uuid(),
    short_name varchar                  not null unique,
    long_name  varchar                  not null unique,
    duration   interval                 not null
);
--;;
create table if not exists data_retrievals (
    id             uuid                     primary key default gen_random_uuid(),
    data_source_id uuid                     not null references data_sources (id),
    exchange_id    uuid                     references exchanges (id),
    retrieved_at   timestamp with time zone not null default now(),
    endpoint       varchar,
    notes          text,
    created_at     timestamp with time zone not null default now()
);
--;;
create index if not exists data_retrievals_source_index on data_retrievals (data_source_id);
--;;
create index if not exists data_retrievals_exchange_index on data_retrievals (exchange_id);
--;;
create index if not exists data_retrievals_retrieved_index on data_retrievals (retrieved_at);
--;;
create table if not exists candlesticks (
    id                uuid                     primary key default gen_random_uuid(),
    numerator_id      uuid                     not null references instruments (id),
    denominator_id    uuid                     not null references instruments (id),
    duration_id       uuid                     not null references candlestick_durations (id),
    data_retrieval_id uuid                     not null references data_retrievals (id),
    time              timestamp with time zone not null,
    open              numeric                  not null,
    high              numeric                  not null,
    low               numeric                  not null,
    close             numeric                  not null,
    volume            numeric,
    adjusted_close    numeric,
    created_at        timestamp with time zone not null default now(),
    unique (numerator_id, denominator_id, duration_id, time, data_retrieval_id),
    check (numerator_id <> denominator_id),
    check (high >= low),
    check (high >= open and high >= close),
    check (low <= open and low <= close),
    check (volume is null or volume >= 0),
    check (adjusted_close is null or adjusted_close >= 0)
);
--;;
create index if not exists candlesticks_query_index on candlesticks (numerator_id, denominator_id, duration_id, time);
--;;
create index if not exists candlesticks_retrieval_index on candlesticks (data_retrieval_id);
